[profile.default]
src = "../contracts"
test = "test"
script = "script"
out = "out"
libs = ["lib"]

remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]

load_dotenv = true


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
