[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "contracts/=../contracts/",
]

load_dotenv = true


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
